/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package queen;

import org.usb4java.LibUsbException;

import queen.exploit.Exploit;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Exploit.runCheckm8();
    }
}
